spring:
    application:
        name: jpa-multi-datasource
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/test1
        username: root
        password: q1w2e3r4
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                highlight_sql: true